import io
import os
from pathlib import Path
from typing import Dict, Any

import numpy as np
from PIL import Image


class FloodDetector:
    def __init__(self, model_path: str | None = None):
        self.model_path = model_path or os.getenv("MODEL_PATH", "models/flood_detection_model.keras")
        self.model = None
        self.model_type = "heuristic"
        self._load_model()

    def _load_model(self) -> None:
        path = Path(self.model_path)
        if not path.exists():
            return

        try:
            import tensorflow as tf

            self.model = tf.keras.models.load_model(str(path))
            self.model_type = "tensorflow"
        except Exception:
            self.model = None
            self.model_type = "heuristic"

    def _preprocess_image(self, image_bytes: bytes) -> np.ndarray:
        image = Image.open(io.BytesIO(image_bytes)).convert("RGB")
        image = image.resize((128, 128))
        array = np.array(image, dtype=np.float32) / 255.0
        return array

    def _heuristic_prediction(self, array: np.ndarray) -> Dict[str, Any]:
        # Lightweight rule-based fallback that works without a trained model.
        brightness = float(array.mean())
        blue_channel = float(array[:, :, 2].mean())
        water_score = 0.55 + (0.25 * (1 - brightness)) + (0.20 * (1 - blue_channel))
        water_score = float(np.clip(water_score, 0.0, 1.0))

        if water_score > 0.6:
            label = "flood"
            confidence = round(float(water_score), 3)
        else:
            label = "no_flood"
            confidence = round(float(1 - water_score), 3)

        return {
            "label": label,
            "confidence": confidence,
            "model_type": self.model_type,
            "message": "Heuristic fallback used because a trained model was not found.",
        }

    def predict(self, image_bytes: bytes) -> Dict[str, Any]:
        array = self._preprocess_image(image_bytes)

        if self.model is not None:
            import tensorflow as tf

            expanded = np.expand_dims(array, axis=0)
            prediction = self.model.predict(expanded, verbose=0)[0][0]
            probability = float(1.0 / (1.0 + np.exp(-prediction)))
            if probability >= 0.5:
                label = "flood"
                confidence = round(float(probability), 3)
            else:
                label = "no_flood"
                confidence = round(float(1.0 - probability), 3)
            return {
                "label": label,
                "confidence": confidence,
                "model_type": self.model_type,
                "message": "Prediction generated by your trained TensorFlow model.",
            }

        return self._heuristic_prediction(array)
